title: ldqnotjustsoso's Homepage
page-top-title: ldqnotjustsoso
top-section-bg-text: Computer Science
home-subtitle: ldqnotjustsoso&ensp;|&ensp;Êùé
copyright-text: '&copy; ldqnotjustsoso 2025-2026. All Rights Reserved.'
